# Generated by Django 5.2.7 on 2025-10-29 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du jeu')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('genre', models.CharField(choices=[('RPG', 'RPG'), ('FPS', 'FPS'), ('METROIDVANIA', 'Metroidvania'), ('VISUAL_NOVEL', 'Visual Novel'), ('PUZZLE', 'Puzzle'), ('ACTION_ADVENTURE', 'Action-Adventure'), ('PLATFORMER', 'Platformer'), ('STRATEGY', 'Strategy'), ('SIMULATION', 'Simulation'), ('HORROR', 'Horror')], max_length=50, verbose_name='Genre')),
                ('theme', models.CharField(choices=[('POST_APOCALYPTIC', 'Post-apocalyptique'), ('CYBERPUNK', 'Cyberpunk'), ('DARK_FANTASY', 'Dark Fantasy'), ('ONIRIC', 'Onirique'), ('STEAMPUNK', 'Steampunk'), ('SPACE', 'Spatial'), ('MEDIEVAL', 'Médiéval'), ('MODERN', 'Moderne'), ('FUTURISTIC', 'Futuriste')], max_length=50, verbose_name='Thème')),
                ('keywords', models.TextField(help_text='Séparés par des virgules', max_length=500, verbose_name='Mots-clés')),
                ('references', models.TextField(blank=True, max_length=500, null=True, verbose_name='Références culturelles')),
                ('universe_description', models.TextField(verbose_name="Description de l'univers")),
                ('story_act1', models.TextField(verbose_name='Histoire - Acte 1')),
                ('story_act2', models.TextField(verbose_name='Histoire - Acte 2')),
                ('story_act3', models.TextField(verbose_name='Histoire - Acte 3')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='games/covers/', verbose_name='Image de couverture')),
                ('is_public', models.BooleanField(default=True, verbose_name='Projet public')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('views_count', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
            ],
            options={
                'verbose_name': 'Jeu',
                'verbose_name_plural': 'Jeux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='games.game', verbose_name='Jeu')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('character_class', models.CharField(max_length=100, verbose_name='Classe/Archétype')),
                ('role', models.CharField(choices=[('PROTAGONIST', 'Protagoniste'), ('ANTAGONIST', 'Antagoniste'), ('MENTOR', 'Mentor'), ('ALLY', 'Allié'), ('NEUTRAL', 'Neutre'), ('RIVAL', 'Rival')], max_length=50, verbose_name='Rôle')),
                ('background', models.TextField(verbose_name='Background/Histoire')),
                ('gameplay_description', models.TextField(verbose_name='Description du gameplay')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/characters/', verbose_name='Image')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='games.game', verbose_name='Jeu')),
            ],
            options={
                'verbose_name': 'Personnage',
                'verbose_name_plural': 'Personnages',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GenerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_type', models.CharField(max_length=50, verbose_name='Type de génération')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Tokens utilisés')),
                ('success', models.BooleanField(default=True, verbose_name='Succès')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Jeu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_history', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de génération',
                'verbose_name_plural': 'Historiques de génération',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du lieu')),
                ('location_type', models.CharField(choices=[('CITY', 'Ville'), ('DUNGEON', 'Donjon'), ('SANCTUARY', 'Sanctuaire'), ('RUINS', 'Ruines'), ('FOREST', 'Forêt'), ('DESERT', 'Désert'), ('CASTLE', 'Château'), ('SPACE_STATION', 'Station spatiale')], max_length=50, verbose_name='Type de lieu')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/locations/', verbose_name='Image')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='games.game', verbose_name='Jeu')),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieux',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-created_at'], name='games_game_created_1d9304_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['slug'], name='games_game_slug_161310_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['is_public'], name='games_game_is_publ_868c71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'game')},
        ),
    ]
